{
  "_type": "doc",
  "_version": 1,
  "_score": null,
  "_source": {
    "b": {
      "app": "*OUR-APP-NAME*",
      "cluster": "aks-cluster",
      "app_version": "0.0.16",
      "container_name": "*OUR-CONTAINER-NAME*",
      "host": "aks-service01",
      "env": "Production",
      "container_image": "*OUR-CONTAINER-NAME*",
      "pod_name": "*OUR-POD-NAME*"
    },
    "agent": {
      "hostname": "aks-service01",
      "name": "aks-service01",
      "type": "filebeat",
      "version": "7.9.0"
    },
    "logzio_codec": "plain",
    "level": "Error",
    "log": {
      "file": {},
      "offset": 2074125
    },
    "@metadata": {
      "beat": "filebeat",
      "type": "_doc",
      "version": "7.9.0"
    },
    "type": "kubernetes",
    "message": "Exception on Receiver sb://QUEUE-NAME during \"Receive\"",
    "exceptions": [
      {
        "StackTraceString": "   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.OnReceiveAsync(Int32 maxMessageCount, TimeSpan serverWaitTime)\n   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.<>c__DisplayClass64_0.<<ReceiveAsync>b__0>d.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at Microsoft.Azure.ServiceBus.RetryPolicy.RunOperation(Func`1 operation, TimeSpan operationTimeout)\n   at Microsoft.Azure.ServiceBus.RetryPolicy.RunOperation(Func`1 operation, TimeSpan operationTimeout)\n   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.ReceiveAsync(Int32 maxMessageCount, TimeSpan operationTimeout)\n   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.ReceiveAsync(TimeSpan operationTimeout)\n   at Microsoft.Azure.ServiceBus.MessageReceivePump.<MessagePumpTaskAsync>b__11_0()",
        "Message": "The operation was canceled.",
        "HResult": -2146233088,
        "ClassName": "Microsoft.Azure.ServiceBus.ServiceBusCommunicationException",
        "RemoteStackIndex": 0,
        "Source": "Microsoft.Azure.ServiceBus",
        "Depth": 0
      },
      {
        "StackTraceString": "   at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)\n   at Microsoft.Azure.Amqp.ReceivingAmqpLink.EndReceiveMessages(IAsyncResult result, IEnumerable`1& messages)\n   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)\n--- End of stack trace from previous location where exception was thrown ---\n   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.OnReceiveAsync(Int32 maxMessageCount, TimeSpan serverWaitTime)",
        "Message": "The operation was canceled.",
        "HResult": -2146233029,
        "ClassName": "System.OperationCanceledException",
        "RemoteStackIndex": 0,
        "Source": "System.Private.CoreLib",
        "Depth": 1
      }
    ],
    "tags": [
      "beats-5015"
    ],
    "input": {
      "type": "container"
    },
    "@timestamp": "2021-03-22T00:45:19.717Z",
    "ecs": {
      "version": "1.5.0"
    },
    "stream": "stdout",
    "fields": {
      "Action": "Receive",
      "InputAddress": "sb://QUEUE-NAME",
      "SourceContext": "MassTransit"
    },
    "messageTemplate": "Exception on Receiver {InputAddress} during {Action}"
  },
  "fields": {
    "@timestamp": [
      "2021-03-22T00:45:19.717Z"
    ]
  },
  "sort": [
    1616373919717
  ]
}